.\"     Title: template
.\"    Author: John McKown
.\" Generator: DocBook XSL Stylesheets v1.70.0 <http://docbook.sf.net/>
.\"      Date:
.\"    Manual: 
.\"    Source: 
.\"
.TH "TEMPLATE" "1" "January, 2012" "z/OS UNIX Utilites from" "John McKown at HealthMarkets"           
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
template \- one line description                          
.SH "SYNOPSIS"
.sp
.RS 3n
.nf
\fBtemplate\fR [OPTION...] \fIdataset\-name\fR
    
.fi
.RE
.SH "DESCRIPTION"
.PP
The
\fBtemplate\fR
command reads a z/OS MVS dataset and writes a stream of data to stdout. Lines (if requested) are produced from dataset records based on the options provided.
.PP
The
\fBtemplate\fR
command runs 
.SH "OPTIONS"
.TP 3n
\fB\-sock\fR

.TP 3n
\fB\-ssh\fR [ssh\-options...] \fIuser@host\fR
.TP 3n
.SH "FILES"
.PP
\fBtemplate\fR
may obtain name matched profile information for a dataset from either a per\-user profile or a system\-wide profile on the z/OS system. For well known
.SH "EXAMPLES"
.SS "Local z/OS Examples"
.SH "SEE ALSO"
.PP
\fBothercmd\fR(1)
.SH "AUTHORS"
.PP
\fBJohn\fR \fBMcKown\fR
.sp -1n
.IP "" 3n
Author.
.PP
.SH "COPYRIGHT"
Copyright \(co 2012, HealthMarkets, Inc.
